version: '3.8'

services:
  # 1. Baza danych MySQL
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306" # Mapujemy na 3307, żeby nie gryzło się z Twoim XAMPP-em
    volumes:
      - db_data:/var/lib/mysql

  # 2. Twoja Aplikacja
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      # Nadpisujemy ustawienia z application.yml dla Dockera
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ecommerce_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # Czekamy aż baza wstanie
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data: